version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
